# Generated by Django 3.2.9 on 2021-11-04 10:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagedata',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='homepagedata',
            name='intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10000, null=True),
        ),
    ]
