# Generated by Django 3.2.9 on 2021-11-04 12:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211104_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, default='/static/images/pic02.jpg', null=True, upload_to='images/cat')),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Catagories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, default='/static/images/pic02.jpg', null=True, upload_to='images/posts')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=True)),
                ('catagory', models.ManyToManyField(blank=True, to='blog.Catagory')),
                ('comments', models.ManyToManyField(blank=True, to='blog.Comment')),
            ],
        ),
    ]
